/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wuyj_com_jnidemo_JNITest */

#ifndef _Included_wuyj_com_jnidemo_JNITest
#define _Included_wuyj_com_jnidemo_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wuyj_com_jnidemo_JNITest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_wuyj_com_jnidemo_JNITest_get
  (JNIEnv *, jobject);

/*
 * Class:     wuyj_com_jnidemo_JNITest
 * Method:    callHelloFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_wuyj_com_jnidemo_JNITest_callHelloFromJava
  (JNIEnv *, jobject);

/*
 * Class:     wuyj_com_jnidemo_JNITest
 * Method:    callAdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_wuyj_com_jnidemo_JNITest_callAdd
  (JNIEnv *, jobject);

/*
 * Class:     wuyj_com_jnidemo_JNITest
 * Method:    callPrintString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_wuyj_com_jnidemo_JNITest_callPrintString
  (JNIEnv *, jobject);

/*
 * Class:     wuyj_com_jnidemo_JNITest
 * Method:    callPrintStaticStr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_wuyj_com_jnidemo_JNITest_callPrintStaticStr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
